query GetUsers($pagination: PaginationInput) {
  getUsers(pagination: $pagination) {
    data {
      id
      email
      name
      isActive
      privileges
      createdAt
    }
    meta {
      total
      page
      limit
    }
  }
}
